api-version: 1.13
name: MvndiMenus
main: com.extendedclip.deluxemenus.DeluxeMenus
version: ${version}
authors: [ HelpChat ]
softdepend: [ PlaceholderAPI, Vault, HeadDatabase, ItemsAdder, Oraxen, ExecutableItems, ExecutableBlocks, Score, MvndiCore ]
description: All in one inventory menu system
commands:
  mvndimenus:
    description: MvndiMenus main commands
    aliases: [ mm, mvndimenu, menu ]
permissions:
  mvndimenus.admin:
    description: admin commands
    default: op
  mvndimenus.open:
    description: open a menu with /mm open <menu>
    default: op
  mvndimenus.open.others:
    description: open a menu with /mm open <menu> <player>
    default: op
  mvndimenus.open.bypass:
    description: attempt to open a menu for a viewer skipping view requirement checking for the player
    default: op
  mvndimenus.menu.*:
    description: permission for all menus
    default: op
  mvndimenus.openrequirement.bypass.*:
    description: Allows the viewer to bypass all menu open requirements
    default: op
  mvndimenus.placeholdersfor:
    description: permission to parse menu placeholders with /mm open <menu> p:<player>
    default: op
  mvndimenus.placeholdersfor.exempt:
    description: exempt from placeholders being parsed when targeted with /dm open <menu p:<player> for players with this permission
    default: op
